"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# --- ตั้งค่า GTK3 สำหรับ WeasyPrint บน Windows ---
if os.name == 'nt': # เช็คว่าเป็น Windows หรือไม่
    # Path นี้ต้องตรงกับที่คุณติดตั้ง GTK3 ไว้จริงในเครื่อง
    GTK_FOLDER = r'C:\Program Files\GTK3-Runtime Win64\bin'
    if os.path.exists(GTK_FOLDER):
        os.environ['PATH'] = GTK_FOLDER + os.pathsep + os.environ.get('PATH', '')
    else:
        # เพิ่มบรรทัดนี้เพื่อเช็คว่าหาเจอไหม
        print(f"❌ หาโฟลเดอร์ GTK3 ไม่เจอที่: {GTK_FOLDER}")    
# -------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-6lj7ufok+msf@gsyt)59-26agm$^ak%1_fs+-zcwu+jx$2*j3b'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

# อ่าน KEY จาก Cloud ถ้าไม่มีให้ใช้ key มั่วๆ ไปก่อน (กัน Error ตอนรันในเครื่อง)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-later')

# ถ้า Cloud บอกว่า DEBUG=False ก็จะเป็น False (Production) ถ้าไม่บอกจะเป็น True (Dev)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'transfer.apps.TransferConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt', # แนะนำให้เพิ่มบรรทัดนี้ด้วยเพื่อความชัดเจน (แม้บางครั้งจะไม่ใส่ก็ทำงานได้)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # เพิ่มเพื่อให้ Django หา template html ได้ง่ายขึ้น
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
   # 'default': {
   #     'ENGINE': 'django.db.backends.postgresql',
   #    'NAME': 'credit_transfer_db',
   #     'USER': 'credit_transfer_user',
   #     'PASSWORD': '1234', 
  #   'HOST': 'localhost',
  #      'PORT': '5433', # ตรวจสอบให้แน่ใจว่า Port นี้ถูกต้อง (ปกติ PostgreSQL ใช้ 5432 แต่ถ้าคุณตั้ง 5433 ก็ใช้ตามนี้)
 #  }
#}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        
        # ส่วนสำคัญ: ต้องเป็น postgres.[รหัสโปรเจกต์]
        'USER': 'postgres.ziqxqckyqvolhezevfei', 
        
        # รหัสผ่านของคุณ (ต้องไม่มีช่องว่าง)
        'PASSWORD': '0965689823teaM',
        
        'HOST': 'aws-1-ap-southeast-1.pooler.supabase.com',
        'PORT': '6543',
    }
}

# 2. ตรวจสอบว่า "เฮ้ย นี่เราอยู่บน Cloud หรือเปล่า?"
# Cloud ส่วนใหญ่จะส่งรหัสลับมาในชื่อ 'DATABASE_URL'
database_url = os.environ.get('DATABASE_URL')

if database_url:
    # 3. ถ้าใช่ (มีรหัสลับส่งมา) แปลว่าอยู่บน Cloud
    # ให้เปลี่ยน (Override) การตั้งค่าไปใช้ PostgreSQL ของ Cloud ทันที
    DATABASES['default'] = dj_database_url.parse(database_url)




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th' # เปลี่ยนเป็นภาษาไทย

TIME_ZONE = 'Asia/Bangkok' # เปลี่ยน Timezone เป็นไทย

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# ตั้งค่า CORS ให้ Frontend เข้าถึงได้
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
CORS_ALLOW_HEADERS = ["Authorization", "Content-Type"]
CORS_ALLOW_CREDENTIALS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = 'static/'

# 👇 เพิ่มบรรทัดนี้ลงไปครับ (เพื่อให้ WhiteNoise ทำงานได้)
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')