# Generated by Django 5.2.6 on 2025-09-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transfer.requestitem')),
                ('suggested_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.course')),
            ],
        ),
    ]
