# Generated by Django 5.2.6 on 2025-09-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_aicomparisonresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.curriculum'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='target_curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.curriculum'),
        ),
    ]
