# Generated by Django 5.2.6 on 2025-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_course_curriculum_transferrequest_target_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_home_institution',
            field=models.BooleanField(default=False),
        ),
    ]
