# Generated by Django 5.2.6 on 2025-09-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_institution_is_home_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
    ]
