# Generated by Django 5.2.6 on 2025-09-25 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_remove_course_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'หลักสูตร (เป้าหมาย)', 'verbose_name_plural': '1. หลักสูตร (เป้าหมาย)'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'สถาบัน (ต้นทาง)', 'verbose_name_plural': '2. สถาบัน (ต้นทาง)'},
        ),
        migrations.RemoveField(
            model_name='aicomparisonresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_home_institution',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='aicomparisonresult',
            name='similarity_score',
            field=models.FloatField(verbose_name='คะแนนความสอดคล้อง'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อหลักสูตร'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อสถาบัน'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='grade',
            field=models.CharField(max_length=5, verbose_name='เกรดที่ได้รับ'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยื่นคำร้อง'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='นักศึกษา'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='target_curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.curriculum', verbose_name='หลักสูตรเป้าหมาย'),
        ),
        migrations.CreateModel(
            name='SourceCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, verbose_name='รหัสวิชา')),
                ('course_name_th', models.CharField(max_length=255, verbose_name='ชื่อวิชา (ไทย)')),
                ('credits', models.IntegerField(verbose_name='หน่วยกิต')),
                ('course_description', models.TextField(verbose_name='คำอธิบายรายวิชา')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.institution', verbose_name='สถาบัน')),
            ],
            options={
                'verbose_name': 'รายวิชาสถาบัน (ต้นทาง)',
                'verbose_name_plural': 'รายวิชาสถาบัน (ต้นทาง)',
            },
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='original_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.sourcecourse', verbose_name='รายวิชาเดิม'),
        ),
        migrations.CreateModel(
            name='TargetCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, verbose_name='รหัสวิชา')),
                ('course_name_th', models.CharField(max_length=255, verbose_name='ชื่อวิชา (ไทย)')),
                ('credits', models.IntegerField(verbose_name='หน่วยกิต')),
                ('course_description', models.TextField(verbose_name='คำอธิบายรายวิชา')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.curriculum', verbose_name='หลักสูตร')),
            ],
            options={
                'verbose_name': 'รายวิชาในหลักสูตร (เป้าหมาย)',
                'verbose_name_plural': 'รายวิชาในหลักสูตร (เป้าหมาย)',
            },
        ),
        migrations.AlterField(
            model_name='aicomparisonresult',
            name='suggested_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.targetcourse', verbose_name='รายวิชาที่แนะนำ'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
