# Generated by Django 5.2.6 on 2025-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='is_viewed_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
