# Generated by Django 5.2.6 on 2025-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_transferrequest_is_viewed_by_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้', 'verbose_name_plural': 'โปรไฟล์ผู้ใช้'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='รหัสนักศึกษา'),
        ),
    ]
