# Generated by Django 5.2.6 on 2025-09-27 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicomparisonresult',
            options={'verbose_name': 'ผลการเปรียบเทียบ AI', 'verbose_name_plural': '4. ผลการเปรียบเทียบ AI'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['name'], 'verbose_name': 'หลักสูตร (เป้าหมาย)', 'verbose_name_plural': '1. หลักสูตร (เป้าหมาย)'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'สถาบัน (ต้นทาง)', 'verbose_name_plural': '2. สถาบัน (ต้นทาง)'},
        ),
        migrations.AlterModelOptions(
            name='requestitem',
            options={'verbose_name': 'รายการวิชาในคำร้อง', 'verbose_name_plural': 'รายการวิชาในคำร้อง'},
        ),
        migrations.AlterModelOptions(
            name='sourcecourse',
            options={'ordering': ['institution', 'course_code'], 'verbose_name': 'รายวิชาสถาบัน', 'verbose_name_plural': '2.1 รายวิชาสถาบัน (ต้นทาง)'},
        ),
        migrations.AlterModelOptions(
            name='targetcourse',
            options={'ordering': ['curriculum', 'course_code'], 'verbose_name': 'รายวิชาในหลักสูตร', 'verbose_name_plural': '1.1 รายวิชาในหลักสูตร (เป้าหมาย)'},
        ),
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'คำร้องเทียบโอน', 'verbose_name_plural': '3. คำร้องเทียบโอน'},
        ),
        migrations.AddField(
            model_name='aicomparisonresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=10, verbose_name='สถานะ'),
        ),
    ]
