# Generated by Django 5.2.6 on 2025-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_alter_aicomparisonresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicomparisonresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'ผลการเปรียบเทียบ AI', 'verbose_name_plural': '4. ผลการเปรียบเทียบ AI'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้', 'verbose_name_plural': '5. โปรไฟล์ผู้ใช้'},
        ),
        migrations.AddField(
            model_name='institution',
            name='is_home_institution',
            field=models.BooleanField(default=False, verbose_name='เป็นสถาบันหลัก (สำหรับหลักสูตรเป้าหมาย)'),
        ),
    ]
