# Generated by Django 5.2.6 on 2025-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_alter_aicomparisonresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicomparisonresult',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลประกอบ'),
        ),
    ]
