# Generated by Django 5.2.6 on 2025-12-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_aicomparisonresult_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขาวิชา'),
        ),
    ]
