# Generated by Django 5.2.6 on 2025-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_userprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='evidence_file',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/', verbose_name='หลักฐานประกอบ (รูปภาพ)'),
        ),
    ]
