# Generated by Django 5.2.6 on 2025-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0016_facultyprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
