# Generated by Django 5.2.6 on 2026-01-19 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0017_requestitem_reject_reason_alter_requestitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'verbose_name': 'ข้อมูลอาจารย์', 'verbose_name_plural': '6. ข้อมูลอาจารย์'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'ข้อมูลนักศึกษา', 'verbose_name_plural': '7. ข้อมูลนักศึกษา'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้ (เดิม)', 'verbose_name_plural': '5. โปรไฟล์ผู้ใช้ (เดิม)'},
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='advisor_room',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='advisor',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='สาขาวิชา'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facultyprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='รหัสนักศึกษา'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('partially_approved', 'อนุมัติบางส่วน'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
