# Generated by Django 5.2.6 on 2026-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0018_alter_facultyprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้ (เก่า)', 'verbose_name_plural': '5. โปรไฟล์ผู้ใช้ (เก่า)'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='สาขาวิชา'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='รหัสนักศึกษา'),
        ),
    ]
